
include:
  - project: 'norsktest/dktools'
    file: '/ci-templates/dkbuild.yml'

py27:
  extends: .testpackage
  script:
    - dk testpackage --ci --django=1.7.11 --tag=py27-dj17

coverage:
  dependencies:
    - py27

wheel:
  dependencies:
    - py27
