language: python

sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"


install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov

script: py.test -v --cov=dkfileutils tests

after_success:
  codecov
